### PR TITLE
For LovyanGFX

### PR DESCRIPTION
**Pull request by riraosan**
@Roger-random 

Hi. Thank you for your Contributions.

I have merged LovyanGFX and ESP_8_BIT_composite in my project. In doing so, I wanted to output signals to GPIO26 (ATOM Lite), so I modified your source.
I decided to define the output port with #define as I don't change it often.
Please merge if you like. I'll commit it for now.

### CODE REVIEW

**Comment by riraosan** [comment]
Could someone please check?

**Comment by Roger-random** [comment]
Please provide more information, I do not understand the issue this pull request intends to solve.

I was not aware of LovyanGFX. A search found https://github.com/lovyan03/LovyanGFX but I saw nothing about composite video. Am I looking at the right thing?

**Comment by riraosan** [comment]
Hi. @Roger-random 

There was a lack of story about my project using your source. Apologies.

My goal is to commit the Panel_CVBS class to LovyanGFX.
I was allowed to use your ESP_8_BIT_composite library in Panel_CVBS. Thank you very much.

Briefly, I have replaced the ESP_8_BIT_GFX class with LovyanGFX in my project. I have not committed to LovyanGFX yet. It is currently under testing.

Here is my inventory project.( using PlatformIO)
https://github.com/riraosan/ESP_8_BIT_composite_Sample.git

The following video shows how it works.
https://twitter.com/i/status/1506231971504013316

The modifications are as follows
- I modified the NTSC signal to switch the output to the PH2.0 port (GPIO26) of ATOM Lite instead of GPIO25. (ENABLE_GPIO26)
- I added a method to enable/disable copyAfterSwap. (setCopyAfterSwap : I didn't want to access the property directly from outside the class.)
- I wanted to write data from Panel_CVBS  in LovyanGFX class to the double buffer, so I added a method. (getComposite)

Best regards.

**Comment by Roger-random** [comment]
Thank you for clarifying.

I spent some time on the README file at https://github.com/lovyan03/LovyanGFX and it appears to have a number of features not in Adafruit's GFX library. In order to fully support the entire LovyanGFX library, I believe it will be better to have a separate Arduino library so we don't incur overhead for people who are not using LovyanGFX.

Option 1:
* Fork this project and remove all references to Adafruit_GFX. Switch to LovyanGFX, and add code to support all LovyanGFX requirements. Submit to Arduino as separate library. Advantage: standalone and optimized for LovyanGFX. Disadvantage: will not pick up future bug fixes of ESP_8_BIT_Composite.

Option 2:
* Create a new project that depends on ESP_8_BIT_Composite project. Create new class that uses an internal instance of ESP_8_BIT_Composite class to draw. (Similar to how ESP_8_BIT_GFX class has a private `_pVideo`) This new class has code to support all LovyanGFX requirements. Advantage: will pick up future features and bug fixes of ESP_8_BIT_Composite library. Disadvantage: includes overhead of Adafruit_GFX.

Since you are still testing LovyanGFX and have not yet committed, I will not merge this pull request until your evaluation is complete. Please let me know what you find in your testing! It would be good to know the advantages/disadvantages of AdafruitGFX vs. LovyanGFX.

In the meantime, I will open a new discussion thread (#31) to see if others want LovyanGFX support.

**Comment by riraosan** [comment]
Hi @Roger-random 
Thanks for your consideration.

I appreciate your advice.
I discussed the pull request with the author of LovyanGFX.
He said that he did not want to add composite output until he had to rely on other libraries to do so.

In the meantime, I would like to contribute to the Arduino community by creating a library that depends on ESP_8_BIT_composite and LovyanGFX.
In other words, I would like to choose option 1, which you mentioned.
May I fork your library and commit it to the Arduno community as a new library?

Best regards.

**Comment by Roger-random** [comment]
Please feel free to fork this library. I've released it under the MIT license to encourage derived work. You don't even have to ask for permission! But thank you for asking.

**Pull request closed without merging**
